In [3]:
import numpy as np
np.zeros(5)  # return a new array of given shape and type, filled with zeroes.

array([0., 0., 0., 0., 0.])

In [5]:
b=np.zeros(6)
b

array([0., 0., 0., 0., 0., 0.])

In [7]:
b.ndim

1

In [11]:
b = np.zeros((3,4,5))
b

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [12]:
b.ndim

3

In [14]:
np.ones((3,4))   # return the array filled with ones.

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
arr  = np.zeros((1,2,3,4))
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [20]:
arr.ndim

4

In [22]:
arr1 = np.ones((3,3))
arr1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
arr1.shape

(3, 3)

In [28]:
# if i want to add 5 to every ele present in array.
add = arr1+5

In [30]:
# similarly we  can do sub,  multi, div in array.
add/2

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [34]:
# if you want to have some specific type of array
np.eye(4)  # return a 2-d array with ones on diagonal and zeros elsewhere.


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [40]:
np.eye(4,3).astype(int)  #  if you want in integer value.

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [42]:
np.eye(4,3, dtype= int)  #  if you want in integer value.

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [47]:
np.empty((3,4))  #return a new array of given shape and type, without intializing entries. it give random value in matrix.

array([[1.10648309e-311, 2.86558075e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.78022341e-306, 3.69776220e-062, 4.75779062e-090,
        8.84698317e+165],
       [1.28275274e+160, 6.12267009e+169, 6.48224659e+170,
        5.82471487e+257]])

In [55]:
# optional
# if you want to make operation with  random number then we have libraary called random
import random
random.choice((1,2,3,4,5))

4

In [57]:
#if you want to select random characetr from string.
random.choice('Rishi')

'R'

In [62]:
random.randrange(1,100) # choose random number b/w limits

44

In [64]:
# if you simply want to create random number then random
random.random()

0.3032733849091729

In [68]:
# if you want to simply suffle the number
lis = [5,6,7,8,9,20]
random.shuffle(lis)
print(lis)

[9, 8, 20, 7, 5, 6]


In [70]:
tup = (1,2,3,4,5)
random.shuffle(tup)
print(tup)

TypeError: 'tuple' object does not support item assignment

In [3]:
import numpy as np
import random 
# if you want to generate uniform value using random . The uniform() method returns a random floating number between the two specified numbers (both included).
random.uniform(10,20)

10.358386767688973

In [5]:
np.array([])

array([], dtype=float64)

In [7]:
#np.random is a module that can be use in place of import random
np.random.random_sample()

0.8098508183703563

In [10]:
# idf you want to generate random number array.
np.random.random_sample((7,))

array([0.26743793, 0.2764545 , 0.44621102, 0.78546172, 0.69184043,
       0.42333046, 0.56857373])

In [12]:
# if you want to generate only one element in array then
np.random.rand(1)

array([0.43356986])

In [14]:
np.random.rand(3,2)

array([[0.28176861, 0.50420119],
       [0.86167438, 0.95539808],
       [0.77639983, 0.9141725 ]])

In [20]:
# if you want to genrate in integer value.
arr = np.random.randint(1,5, size=(2,3)) # it gen integer value b/w 1 to 5 b/w 2 rows and 3 coloumn .

In [22]:
arr.ndim

2

In [24]:
arr.shape

(2, 3)

In [26]:
arr.size

6

In [28]:
# if we want to change the shape of array.
arr.reshape(3,2)

array([[1, 1],
       [4, 4],
       [1, 4]], dtype=int32)

In [31]:
arr1 = arr  # if we change the shape then size will noy change.
arr1.size

6

In [33]:
#array size will noy change, always reshape parameter should be multiplication of original array
arr.shape

(2, 3)

In [35]:
arr.size

6

In [37]:
arr.reshape(1,5) 

ValueError: cannot reshape array of size 6 into shape (1,5)

In [39]:
arr.reshape(1,6)

array([[1, 1, 4, 4, 1, 4]], dtype=int32)

In [44]:
#case when you don't know in reshape what should be the column count or row count we can insert any negative number.
arr.reshape(1,-1)

array([[1, 1, 4, 4, 1, 4]], dtype=int32)

In [46]:
arr.reshape(2,-1)

array([[1, 1, 4],
       [4, 1, 4]], dtype=int32)

In [48]:
arr.reshape(-1,2)

array([[1, 1],
       [4, 4],
       [1, 4]], dtype=int32)

In [51]:
arr.reshape(-10,3)

array([[1, 1, 4],
       [4, 1, 4]], dtype=int32)

In [53]:
arr.reshape(-10,3).base # to see the orginal array.

array([[1, 1, 4],
       [4, 1, 4]], dtype=int32)

In [55]:
arr8 = np.array([1,2,3,4])
c_arr8 = arr8.reshape(2,2)  # Reshape into (2,2) without copying
print(c_arr8.base)    # Should return the original array

[1 2 3 4]


In [63]:
arr = np.arange(6).reshape(2, 3)
copied_arr = arr.copy().reshape(3, 2).copy()  # Copy first, then reshape
print(copied_arr.base)  # Should return None


None


In [5]:
#condition on array
import numpy as np
import random
arr1 = np.random.randint(5,15,(3,4))
arr1

array([[10, 10,  8,  7],
       [ 9, 10,  9,  6],
       [10, 13,  7, 12]], dtype=int32)

In [7]:
arr1 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False,  True]])

In [9]:
# if we want to see value in array ele not in boolean
arr1[arr1 > 10]

array([13, 12], dtype=int32)

In [11]:
arr1[2]

array([10, 13,  7, 12], dtype=int32)

In [13]:
arr1[1][3]

np.int32(6)

In [16]:
#if you want to show continuation of row then you can use string slicing
arr1[1:3]

array([[ 9, 10,  9,  6],
       [10, 13,  7, 12]], dtype=int32)

In [18]:
arr1

array([[10, 10,  8,  7],
       [ 9, 10,  9,  6],
       [10, 13,  7, 12]], dtype=int32)

In [23]:
arr1[1:3,[1,3]]  # 1th row and 2nd row , 1 col and 3 col

array([[10,  6],
       [13, 12]], dtype=int32)

In [26]:
arr1[0:3,[0,3]]

array([[10,  7],
       [ 9,  6],
       [10, 12]], dtype=int32)

In [27]:
# slicing on both rows and column

In [29]:
arr1[0:2, 1:3]

array([[10,  8],
       [10,  9]], dtype=int32)

In [31]:
arr1[0:2, [1,3]]

array([[10,  7],
       [10,  6]], dtype=int32)

In [33]:
arr1

array([[10, 10,  8,  7],
       [ 9, 10,  9,  6],
       [10, 13,  7, 12]], dtype=int32)

In [35]:
arr1[0][0]

np.int32(10)

In [43]:
arr1[[0,2],[0,3]]

array([10, 12], dtype=int32)

In [50]:
# mathematical operation between two arrays.
arr1 = np.random.randint(5,15,(3,3))
arr2 = np.random.randint(15,25,(3,3))

In [46]:
arr1

array([[ 7, 10,  5],
       [ 7, 10,  8],
       [11, 12, 12]], dtype=int32)

In [48]:
arr2

array([[20, 15, 17],
       [16, 21, 21],
       [21, 17, 23]], dtype=int32)

In [51]:
arr1-arr2

array([[-12, -16,  -8],
       [ -5,  -8, -11],
       [-13,  -8,  -2]], dtype=int32)

In [53]:
arr1+arr2

array([[24, 30, 28],
       [27, 28, 21],
       [31, 32, 28]], dtype=int32)

In [55]:
arr1/arr2   # index wise array divison.

array([[0.33333333, 0.30434783, 0.55555556],
       [0.6875    , 0.55555556, 0.3125    ],
       [0.40909091, 0.6       , 0.86666667]])

In [57]:
arr1*arr2  # index wise array multiplication.

array([[108, 161, 180],
       [176, 180,  80],
       [198, 240, 195]], dtype=int32)

In [60]:
#matric multiplication >> different from index wise multiplication.
arr1 @ arr2  # 1st way of doing matrix multipliaction.

array([[440, 464, 370],
       [468, 533, 433],
       [640, 683, 549]], dtype=int32)

In [62]:
np.dot(arr1,arr2) #2nd way.  matrix multiplication can also be called as dot product

array([[440, 464, 370],
       [468, 533, 433],
       [640, 683, 549]], dtype=int32)

In [64]:
arr1/0 # in python if we divide a number by 0 then it became give zero divison error  and when comes to panda then it give infinity. 

C:\Users\Rishi Raj\AppData\Local\Temp\ipykernel_14500\408271498.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 # in python if we divide a number by 0 then it became give zero divison error  and when comes to panda then it give infinity.


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [68]:
#broadcasting
arr5 = np.zeros((3,4))
arr5

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
c = np.array([1,2,3,4])

In [78]:
r = arr5+c
print(r)

[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


In [80]:
r.astype(int)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [84]:
r.T.astype(int)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [86]:
# if we want to find square root of every ele
np.sqrt(r)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

In [88]:
np.log10(r) # find log value w.r.t to base 10.

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.        , 0.30103   , 0.47712125, 0.60205999]])

In [90]:
np.exp(r)  # np. exp() calculates e^x for each value of x in your input array

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

In [92]:
np.min(r)

np.float64(1.0)

In [94]:
np.max(r)

np.float64(4.0)