In [2]:
#NUMPY >> NUMERICAL PYHTON it is built in 2005 by Travis OLiphant
import numpy as np
np.__version__

'2.2.1'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
lis= [1,2,3,"pwskills",3+5j,True,1.2]

In [5]:
type(lis)

list

In [6]:
lis

[1, 2, 3, 'pwskills', (3+5j), True, 1.2]

In [ ]:
#Numpy stores the data in array
#An array is a container used to store the data of same data type.

In [ ]:
#Why numpy?
#Computation is fast >> due to array>> contiguous meemory location.
#mathematical computation

In [9]:
lst = [1,2,3,4]

In [10]:
arr = np.array(lst)

In [12]:
arr

array([1, 2, 3, 4])

In [16]:
lst = [1,2,3,4,5.1]
arr = np.array(lst)
arr

array([1. , 2. , 3. , 4. , 5.1])

In [18]:
lst = [1,2,3,4,'5.1','Rishi']
arr = np.array(lst)
arr

array(['1', '2', '3', '4', '5.1', 'Rishi'], dtype='<U21')

In [19]:
#arr store homogenous data.

In [21]:
type(arr) # here ndarray stands for n dimension array

numpy.ndarray

In [23]:
arr.ndim

1

In [25]:
lst1 = [[1,2,3],[4,5,6]]
arr2 = np.array(lst1)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr2.ndim

2

In [7]:
# Matrix is the way to reprsent the data in vector form. it is specialised array,2 dimensional 
np.matrix([1,2,3,4])  

matrix([[1, 2, 3, 4]])

In [6]:
mat = np.matrix([1,2,3,4])   # A matrix can't has 3d dimension.
type(mat) 

numpy.matrix

In [35]:
arr2 = np.matrix([[1,2,3,4,5],[6,7,8,9,10]])
arr2

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [39]:
arr3 = np.matrix([[1,2],[3,4],[5,6]])
arr3

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [40]:
arr4 =np.matrix([[[1,2], [3,4], [5,6]]])
arr4

ValueError: matrix must be 2-dimensional

In [50]:
#more way to convert array
l = [1,2,3]
np.asarray(l)

array([1, 2, 3])

In [51]:
mat

matrix([[1, 2, 3, 4]])

In [49]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [4]:
import numpy as np
np.asanyarray([1,2,3])  #only convert those which are not in array if it is already a subclass of array then it should convert it intoi array.


array([1, 2, 3])

In [9]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [11]:
t = ([1,2,3],[4,5,6])   #tuple to array

In [13]:
type(t)

tuple

In [15]:
np.asanyarray(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
np.asarray(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [25]:
arr[4] = 6
arr

array([1, 2, 3, 4, 6])

In [26]:
b = arr
b

array([1, 2, 3, 4, 6])

In [28]:
arr[3] = 10
b   # change in array lead to chnage in b >> shallow copy >> arr and b are pointing to the same memory block that's why if a change in arr occur will cause change in a also.

array([ 1,  2,  3, 10,  6])

In [29]:
a = arr.copy()
arr[2] = 15
a  # chnage in array not lead to change in a >> deep copy >> a is pointing to copy of arr so any chnage in arr will not cause change in a. 

array([ 1,  2,  3, 10,  6])

In [31]:
arr

array([ 1,  2, 15, 10,  6])

In [32]:
#To create an array >> np.array, np.asanarray, np.asanyarray

In [43]:
arr3 = np.fromfunction(lambda i,j : i==j, (3,3)) #construct an array by executing a function over each coordinate.
arr3

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [38]:
arr3.ndim

2

In [41]:
# to know rows and coloumn in arrays
arr3.shape

(3, 3)

In [44]:
# to check number of elements
arr3.size

9

In [46]:
arr4 = np.fromfunction(lambda x,y : x!=y, (4,4))
arr4

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [50]:
arr5 = np.fromfunction(lambda x,y : x/y, (4,4))
arr5

C:\Users\Rishi Raj\AppData\Local\Temp\ipykernel_15280\1594754160.py:1: RuntimeWarning: divide by zero encountered in divide
  arr5 = np.fromfunction(lambda x,y : x/y, (4,4))
C:\Users\Rishi Raj\AppData\Local\Temp\ipykernel_15280\1594754160.py:1: RuntimeWarning: invalid value encountered in divide
  arr5 = np.fromfunction(lambda x,y : x/y, (4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [51]:
# array make form iterables
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [52]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
(i for i in range(10))  # generate objects by the help of iterables

<generator object <genexpr> at 0x000001FDE1642140>

In [60]:
list(i for i in range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [67]:
iterable = (i for i in range(10))
iterable

<generator object <genexpr> at 0x000001FDC2BF7940>

In [68]:
np.fromiter(iterable, int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.fromstring('22 23 24', sep =" ")

array([22., 23., 24.])

In [73]:
np.fromstring('22 23 24', sep =" ").astype(int)  # this method work with int, float value not string value.

array([22, 23, 24])

In [75]:
s = 'skjdiu dushhu duhew'
result = s.split(' ')
np.array(result)

array(['skjdiu', 'dushhu', 'duhew'], dtype='<U6')

In [77]:
range(6)

range(0, 6)

In [79]:
list(range(6))

[0, 1, 2, 3, 4, 5]

In [83]:
# similar in numpy we have arange function >> to generate sequence of number
np.arange(5,15, 4)

array([ 5,  9, 13])

In [86]:
np.linspace(5,15,8) # retrurn evenly spaced over a specified interval.
#give me 8 numbers b/w 5 and 15 evenly spaced

array([ 5.        ,  6.42857143,  7.85714286,  9.28571429, 10.71428571,
       12.14285714, 13.57142857, 15.        ])

In [88]:
np.logspace(1,5,10) #return numbers spaced evenly on a log scale, base is 10

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])